// <auto-generated />
using System;
using AutoskolaApp.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoskolaApp.Migrations
{
    [DbContext(typeof(AutoskolaDbContext))]
    partial class AutoskolaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("AutoskolaApp.Models.Administrator", b =>
                {
                    b.Property<Guid>("IDAdministratora")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OIB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDAdministratora");

                    b.ToTable("Administratori");
                });

            modelBuilder.Entity("AutoskolaApp.Models.Instruktor", b =>
                {
                    b.Property<Guid>("IDInstruktor")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumZaposlenja")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Napomena")
                        .HasColumnType("TEXT");

                    b.Property<string>("OIB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDInstruktor");

                    b.ToTable("Instruktori");
                });

            modelBuilder.Entity("AutoskolaApp.Models.Ispit", b =>
                {
                    b.Property<Guid>("IDIspita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstruktorIDInstruktor")
                        .HasColumnType("TEXT");

                    b.Property<string>("VrstaIspita")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDIspita");

                    b.HasIndex("InstruktorIDInstruktor");

                    b.ToTable("Ispiti");
                });

            modelBuilder.Entity("AutoskolaApp.Models.Korisnik", b =>
                {
                    b.Property<Guid>("IDKorisnika")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UlogaIDUloge")
                        .HasColumnType("TEXT");

                    b.HasKey("IDKorisnika");

                    b.HasIndex("UlogaIDUloge");

                    b.ToTable("Korisnici");
                });

            modelBuilder.Entity("AutoskolaApp.Models.PolaznikIspita", b =>
                {
                    b.Property<Guid>("IDPolaznika")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IspitIDIspita")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rezultat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StudentIDStudenta")
                        .HasColumnType("TEXT");

                    b.HasKey("IDPolaznika");

                    b.HasIndex("IspitIDIspita");

                    b.HasIndex("StudentIDStudenta");

                    b.ToTable("PolazniciIspita");
                });

            modelBuilder.Entity("AutoskolaApp.Models.Student", b =>
                {
                    b.Property<Guid>("IDStudenta")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumPocetka")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OIB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SatiVoznje")
                        .HasColumnType("INTEGER");

                    b.HasKey("IDStudenta");

                    b.ToTable("Studenti");
                });

            modelBuilder.Entity("AutoskolaApp.Models.Uloga", b =>
                {
                    b.Property<Guid>("IDUloge")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImeUloge")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDUloge");

                    b.ToTable("Uloge");

                    b.HasData(
                        new
                        {
                            IDUloge = new Guid("bbb87d3f-4ca2-46e9-bc0b-7fd0e3d25d77"),
                            ImeUloge = "Administrator"
                        },
                        new
                        {
                            IDUloge = new Guid("33eae27b-fb07-4267-bba0-2e5d16e056a4"),
                            ImeUloge = "Instruktor"
                        },
                        new
                        {
                            IDUloge = new Guid("7ff139de-2cdc-421c-853c-c9b7773a89f6"),
                            ImeUloge = "Student"
                        });
                });

            modelBuilder.Entity("AutoskolaApp.Models.Uplata", b =>
                {
                    b.Property<Guid>("IDUplate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumUplate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Iznos")
                        .HasColumnType("TEXT");

                    b.Property<string>("NacinUplate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StudentIDStudenta")
                        .HasColumnType("TEXT");

                    b.HasKey("IDUplate");

                    b.HasIndex("StudentIDStudenta");

                    b.ToTable("Uplate");
                });

            modelBuilder.Entity("AutoskolaApp.Models.Vozilo", b =>
                {
                    b.Property<string>("Registracija")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstruktorIDInstruktor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Registracija");

                    b.HasIndex("InstruktorIDInstruktor");

                    b.ToTable("Vozila");
                });

            modelBuilder.Entity("AutoskolaApp.Models.Voznja", b =>
                {
                    b.Property<Guid>("IDVoznje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumVoznje")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstruktorIDInstruktor")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StudentIDStudenta")
                        .HasColumnType("TEXT");

                    b.HasKey("IDVoznje");

                    b.HasIndex("InstruktorIDInstruktor");

                    b.HasIndex("StudentIDStudenta");

                    b.ToTable("Voznje");
                });

            modelBuilder.Entity("AutoskolaApp.Models.Administrator", b =>
                {
                    b.HasOne("AutoskolaApp.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("IDAdministratora")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("AutoskolaApp.Models.Instruktor", b =>
                {
                    b.HasOne("AutoskolaApp.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("IDInstruktor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("AutoskolaApp.Models.Ispit", b =>
                {
                    b.HasOne("AutoskolaApp.Models.Instruktor", "Instruktor")
                        .WithMany("Ispiti")
                        .HasForeignKey("InstruktorIDInstruktor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instruktor");
                });

            modelBuilder.Entity("AutoskolaApp.Models.Korisnik", b =>
                {
                    b.HasOne("AutoskolaApp.Models.Uloga", "Uloga")
                        .WithMany("Korisnici")
                        .HasForeignKey("UlogaIDUloge")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uloga");
                });

            modelBuilder.Entity("AutoskolaApp.Models.PolaznikIspita", b =>
                {
                    b.HasOne("AutoskolaApp.Models.Ispit", "Ispit")
                        .WithMany("PolazniciIspita")
                        .HasForeignKey("IspitIDIspita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoskolaApp.Models.Student", "Student")
                        .WithMany("PolazniciIspita")
                        .HasForeignKey("StudentIDStudenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ispit");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AutoskolaApp.Models.Student", b =>
                {
                    b.HasOne("AutoskolaApp.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("IDStudenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("AutoskolaApp.Models.Uplata", b =>
                {
                    b.HasOne("AutoskolaApp.Models.Student", "Student")
                        .WithMany("Uplate")
                        .HasForeignKey("StudentIDStudenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AutoskolaApp.Models.Vozilo", b =>
                {
                    b.HasOne("AutoskolaApp.Models.Instruktor", "Instruktor")
                        .WithMany()
                        .HasForeignKey("InstruktorIDInstruktor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instruktor");
                });

            modelBuilder.Entity("AutoskolaApp.Models.Voznja", b =>
                {
                    b.HasOne("AutoskolaApp.Models.Instruktor", "Instruktor")
                        .WithMany()
                        .HasForeignKey("InstruktorIDInstruktor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoskolaApp.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentIDStudenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instruktor");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AutoskolaApp.Models.Instruktor", b =>
                {
                    b.Navigation("Ispiti");
                });

            modelBuilder.Entity("AutoskolaApp.Models.Ispit", b =>
                {
                    b.Navigation("PolazniciIspita");
                });

            modelBuilder.Entity("AutoskolaApp.Models.Student", b =>
                {
                    b.Navigation("PolazniciIspita");

                    b.Navigation("Uplate");
                });

            modelBuilder.Entity("AutoskolaApp.Models.Uloga", b =>
                {
                    b.Navigation("Korisnici");
                });
#pragma warning restore 612, 618
        }
    }
}
