// <auto-generated />
using System;
using AutoskolaApp.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoskolaApp.Migrations
{
    [DbContext(typeof(AutoskolaDbContext))]
    partial class AutoskolaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("AutoskolaApp.Models.Administrator", b =>
                {
                    b.Property<int>("IDAdministratora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IDKorisnika")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OIB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDAdministratora");

                    b.HasIndex("IDKorisnika")
                        .IsUnique();

                    b.ToTable("Administratori");

                    b.HasData(
                        new
                        {
                            IDAdministratora = 1,
                            IDKorisnika = 1,
                            Ime = "Vid",
                            OIB = "17232937055",
                            Prezime = "Piljek"
                        });
                });

            modelBuilder.Entity("AutoskolaApp.Models.Instruktor", b =>
                {
                    b.Property<int>("IDInstruktora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatumZaposlenja")
                        .HasColumnType("TEXT");

                    b.Property<int>("IDKorisnika")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Napomena")
                        .HasColumnType("TEXT");

                    b.Property<string>("OIB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDInstruktora");

                    b.HasIndex("IDKorisnika")
                        .IsUnique();

                    b.ToTable("Instruktori");

                    b.HasData(
                        new
                        {
                            IDInstruktora = 1,
                            DatumZaposlenja = new DateTime(2020, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IDKorisnika = 2,
                            Ime = "Leon",
                            OIB = "17235938955",
                            Prezime = "Plecko"
                        });
                });

            modelBuilder.Entity("AutoskolaApp.Models.Ispit", b =>
                {
                    b.Property<int>("IDIspita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("IDInstruktora")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VrstaIspita")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDIspita");

                    b.ToTable("Ispiti");
                });

            modelBuilder.Entity("AutoskolaApp.Models.Korisnik", b =>
                {
                    b.Property<int>("IDKorisnika")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IDUloge")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDKorisnika");

                    b.HasIndex("IDUloge");

                    b.ToTable("Korisnici");

                    b.HasData(
                        new
                        {
                            IDKorisnika = 1,
                            IDUloge = 1,
                            KorisnickoIme = "admin",
                            Lozinka = "adminautoskola"
                        },
                        new
                        {
                            IDKorisnika = 2,
                            IDUloge = 1,
                            KorisnickoIme = "instruktortest",
                            Lozinka = "instruktortest"
                        });
                });

            modelBuilder.Entity("AutoskolaApp.Models.PolaznikIspita", b =>
                {
                    b.Property<int>("IDPolaznika")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IDIspita")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IDStudenta")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rezultat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDPolaznika");

                    b.HasIndex("IDIspita");

                    b.HasIndex("IDStudenta");

                    b.ToTable("PolazniciIspita");
                });

            modelBuilder.Entity("AutoskolaApp.Models.Student", b =>
                {
                    b.Property<int>("IDStudenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatumPocetka")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("TEXT");

                    b.Property<int>("IDKorisnika")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OIB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SatiVoznje")
                        .HasColumnType("INTEGER");

                    b.HasKey("IDStudenta");

                    b.HasIndex("IDKorisnika")
                        .IsUnique();

                    b.ToTable("Studenti");
                });

            modelBuilder.Entity("AutoskolaApp.Models.Uloga", b =>
                {
                    b.Property<int>("IDUloge")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImeUloge")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDUloge");

                    b.ToTable("Uloge");

                    b.HasData(
                        new
                        {
                            IDUloge = 1,
                            ImeUloge = "Administrator"
                        },
                        new
                        {
                            IDUloge = 2,
                            ImeUloge = "Instruktor"
                        },
                        new
                        {
                            IDUloge = 3,
                            ImeUloge = "Student"
                        });
                });

            modelBuilder.Entity("AutoskolaApp.Models.Uplata", b =>
                {
                    b.Property<int>("IDUplate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatumUplate")
                        .HasColumnType("TEXT");

                    b.Property<int>("IDStudenta")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Iznos")
                        .HasColumnType("TEXT");

                    b.Property<string>("NacinUplate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDUplate");

                    b.HasIndex("IDStudenta");

                    b.ToTable("Uplate");
                });

            modelBuilder.Entity("AutoskolaApp.Models.Vozilo", b =>
                {
                    b.Property<string>("Registracija")
                        .HasColumnType("TEXT");

                    b.Property<int>("IDInstruktora")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Registracija");

                    b.HasIndex("IDInstruktora")
                        .IsUnique();

                    b.ToTable("Vozila");
                });

            modelBuilder.Entity("AutoskolaApp.Models.Voznja", b =>
                {
                    b.Property<int>("IDVoznje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatumVoznje")
                        .HasColumnType("TEXT");

                    b.Property<int>("IDInstruktora")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IDStudenta")
                        .HasColumnType("INTEGER");

                    b.HasKey("IDVoznje");

                    b.ToTable("Voznje");
                });

            modelBuilder.Entity("AutoskolaApp.Models.Administrator", b =>
                {
                    b.HasOne("AutoskolaApp.Models.Korisnik", "Korisnik")
                        .WithOne("Administrator")
                        .HasForeignKey("AutoskolaApp.Models.Administrator", "IDKorisnika")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("AutoskolaApp.Models.Instruktor", b =>
                {
                    b.HasOne("AutoskolaApp.Models.Korisnik", "Korisnik")
                        .WithOne("Instruktor")
                        .HasForeignKey("AutoskolaApp.Models.Instruktor", "IDKorisnika")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("AutoskolaApp.Models.Ispit", b =>
                {
                    b.HasOne("AutoskolaApp.Models.Instruktor", "Instruktor")
                        .WithMany("Ispiti")
                        .HasForeignKey("IDIspita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instruktor");
                });

            modelBuilder.Entity("AutoskolaApp.Models.Korisnik", b =>
                {
                    b.HasOne("AutoskolaApp.Models.Uloga", "Uloga")
                        .WithMany("Korisnici")
                        .HasForeignKey("IDUloge")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uloga");
                });

            modelBuilder.Entity("AutoskolaApp.Models.PolaznikIspita", b =>
                {
                    b.HasOne("AutoskolaApp.Models.Ispit", "Ispit")
                        .WithMany("PolazniciIspita")
                        .HasForeignKey("IDIspita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoskolaApp.Models.Student", "Student")
                        .WithMany("PolazniciIspita")
                        .HasForeignKey("IDStudenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ispit");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AutoskolaApp.Models.Student", b =>
                {
                    b.HasOne("AutoskolaApp.Models.Korisnik", "Korisnik")
                        .WithOne("Student")
                        .HasForeignKey("AutoskolaApp.Models.Student", "IDKorisnika")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("AutoskolaApp.Models.Uplata", b =>
                {
                    b.HasOne("AutoskolaApp.Models.Student", "Student")
                        .WithMany("Uplate")
                        .HasForeignKey("IDStudenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AutoskolaApp.Models.Vozilo", b =>
                {
                    b.HasOne("AutoskolaApp.Models.Instruktor", "Instruktor")
                        .WithOne("Vozilo")
                        .HasForeignKey("AutoskolaApp.Models.Vozilo", "IDInstruktora")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instruktor");
                });

            modelBuilder.Entity("AutoskolaApp.Models.Voznja", b =>
                {
                    b.HasOne("AutoskolaApp.Models.Instruktor", "Instruktor")
                        .WithMany("Voznje")
                        .HasForeignKey("IDVoznje")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoskolaApp.Models.Student", "Student")
                        .WithMany("Voznje")
                        .HasForeignKey("IDVoznje")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instruktor");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AutoskolaApp.Models.Instruktor", b =>
                {
                    b.Navigation("Ispiti");

                    b.Navigation("Vozilo");

                    b.Navigation("Voznje");
                });

            modelBuilder.Entity("AutoskolaApp.Models.Ispit", b =>
                {
                    b.Navigation("PolazniciIspita");
                });

            modelBuilder.Entity("AutoskolaApp.Models.Korisnik", b =>
                {
                    b.Navigation("Administrator");

                    b.Navigation("Instruktor");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AutoskolaApp.Models.Student", b =>
                {
                    b.Navigation("PolazniciIspita");

                    b.Navigation("Uplate");

                    b.Navigation("Voznje");
                });

            modelBuilder.Entity("AutoskolaApp.Models.Uloga", b =>
                {
                    b.Navigation("Korisnici");
                });
#pragma warning restore 612, 618
        }
    }
}
